{% set version = '0.0-2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-assertive.files
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive.files_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.files/assertive.files_{{ version }}.tar.gz
  sha256: be6adda6f18a0427449249e44c2deff4444a123244b16fe82c92f15d24faee0a

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.numbers
  run:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.numbers

test:
  commands:
    - $R -e "library('assertive.files')"           # [not win]
    - "\"%R%\" -e \"library('assertive.files')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.files
  license: GPL-3.0-or-later
  summary: A set of predicates and assertions for checking the properties of files and connections.  This
    is mainly for use by other package developers who want to include run-time testing
    features in their own packages. End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
